### ISSUE TITLE
Cypress frequently throws a [warning] Unexpected input

### ISSUE THREAD

**Issue by DlgSHi** [cypress-io/github-action#141]
We have set-up the cypress run for GitHub Actions using your examples. But yesterday it starts failing with en errors as below:
<img width="1078" alt="Screenshot 2020-05-14 at 09 22 51" src="https://user-images.githubusercontent.com/34001198/81905735-6c856980-95c5-11ea-89ae-07151f0bda1f.png">

Link to [Actions](https://github.com/Sage/carbon/runs/673523613?check_suite_focus=true) for our project

@bahmutov , @brian-mann  any thoughts ?

**Comment by DlgSHi** [comment]
An issue was with different `env` parameters sent from difference GitHub Actions `jobs`. Fixed with implementing [docker container](https://github.com/cypress-io/github-action#docker-image) as `env`.

**Comment by leosuncin** [comment]
I believe is because those inputs are not defined in `action.yml`

https://github.com/cypress-io/github-action/blob/4fdf3ee729c31daf9a39e658802bf63b04721c1c/action.yml#L5-L25

**Comment by jennifer-shehane** [comment]
Have this issue been resolved? Can this issue be closed?

**Comment by jebendfds** [comment]
@jennifer-shehane We are still experiencing this issue. Your documentation says to use the working directory parameter to specify the cypress folder in monorepos, yet the parameter is unrecognized.

Can you elaborate more on your solution @DlgSHi ?

**Comment by DlgSHi** [comment]
The solution is about setting the save env for every `job` on the GitHub Actions using docker image. But not about `warnings`

**Comment by prescottprue** [comment]
@jennifer-shehane No, it is not yet resolved. As @leosuncin mentioned, I believe it is due to the settings not being in `action.yml` - I made [a PR](https://github.com/cypress-io/github-action/pull/143) to include a number of the missing inputs

**Comment by craig-dae** [comment]
We have started having this problem yesterday. All pipelines have started failing.

**Comment by prescottprue** [comment]
@craig-dae I provided a PR for fixing the warnings mentioned above, so now it should just be a matter of getting it merged. If it ends up taking a little while longer I can merge in my fork so that can be pointed to in the meantime

**Comment by craig-dae** [comment]
@prescottprue So actually, I am thinking my issue is different, and I should re-open my issue report. I thought that these warnings were causing my issue, but I just looked, and these warnings have been appearing long before my pipeline stopped working.

**Comment by calebeby** [comment]
Thanks @prescottprue for your fix, looks great! It would be great if someone from Cypress could merge that

**Comment by DlgSHi** [comment]
No more warnings as above, thanks :)
One more `new` warning appears :(

**Comment by DlgSHi** [comment]
Made a [PR](https://github.com/cypress-io/github-action/pull/146) to fix that warning

**Comment by DlgSHi** [comment]
After release v.1.24.3 - no more warnings in console :) Thanks guys, closing an issue

**Comment by myildizCH** [comment]
Sometimes it is just enough to clean everything and reinstall. Please follow the steps below if you can't find any solution:
• Go to the project directory
• Remove the node_modules directory: `rm -rf node_modules`.
• Remove package-lock.json file: `rm package-lock.json`
• Clear the cache: `npm cache clean --force`
• Run `npm install --verbose`
